"""
Django settings for sga_fisi project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7l4gb)@pep8(9g#zfmq9+yo^@6(b7bgi-5$x%vl#n)8-54da=a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'general',
    'escuela',
    'administrativo',
    'vicerrectorado',
    'import_export',
]

JAZZMIN_SETTINGS = {
    "site_title": "SGA FISI",
    "site_header": "SGA FISI",
    "site_brand": "SGA FISI",
    "site_logo": "/web/img/logo.webp",
    "login_logo": "/web/img/logo.webp",
    "site_icon": "/web/img/logo.webp",
    "welcome_sign": "Bienvenidos al Sistema de Gestion Administrativa - FISI",
    # "topmenu_links": [

    #     # Url that gets reversed (Permissions can be added)
    #     {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

    #     # external url that opens in a new window (Permissions can be added)
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

    #     # model admin to link to (Permissions checked against model)
    #     {"model": "auth.User"},

    #     # App with dropdown menu to all its models pages (Permissions checked against models)
    #     {"app": "web"},
    # ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "escuela.Curso": "fas fa-book",
        "escuela.CursoEquivalente": "fas fa-book",
        "general.Dia": "fas fa-calendar",
        "escuela.Grupo": "fas fa-users",
        "administrativo.GrupoHorario" : "fas fa-calendar",
        "administrativo.Aula" : "fas fa-school",
        "administrativo.Local" : "fas fa-school",
        "vicerrectorado.Semestre" : "fas fa-calendar",
        "escuela.CursoTipodictado" : "fas fa-book",
        "general.Facultad" : "fas fa-school",
        "general.Escuela" : "fas fa-school",
        "escuela.PlanEstudio" : "fas fa-file",
        "escuela.TipoCurso" : "fas fa-file",
        "escuela.CursoHorasDictado" : "fas fa-clock",
        "general.AreaAcademica" : "fas fa-font",
        "escuela.CursoTipo" : "fas fa-laptop",
        "escuela.CursoPrerequisito" : "fas fa-arrow-left",
    },
    "usermenu_links": [
        {"model": "auth.user"}
    ],
    "copyright": "Facultad de Ingenieria de Sistemas e Informatica",
    "user_avatar": None,
    "order_with_respect_to": ["web.Semestre", "web.Local", "web.Aula", "web.Dia", "web.Curso", "web.CursoEquivalente", "web.Grupo", "web.GrupoHorario", "web.CursoTipoDictado"],
}

#JAZZMIN_SETTINGS["show_ui_builder"] = True
JAZZMIN_UI_TWEAKS = {
    "theme": "litera",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sga_fisi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sga_fisi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sga_fisi',
        'USER': 'root',
        'PASSWORD': '1234',
        'HOST':'localhost',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-PE'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# Absolute filesystem path to the directory that will hold static files.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
