# Generated by Django 4.2.7 on 2023-11-12 23:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('vicerrectorado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cur_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cur_vcCodigo', models.CharField(max_length=16, verbose_name='Código')),
                ('cur_vcNombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('cur_fCreditos', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Créditos')),
                ('cur_fCreditosRequisito', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Créditos requeridos')),
                ('cur_iSemestre', models.IntegerField(blank=True, null=True, verbose_name='Semestre')),
                ('curare_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.areaacademica', verbose_name='Área académica')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='CursoTipo',
            fields=[
                ('curtip_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('curtip_vcNombre', models.CharField(max_length=32, unique=True, verbose_name='Nombre')),
                ('curtip_bActivo', models.IntegerField(default=1, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de curso',
                'verbose_name_plural': 'Tipos de curso',
                'db_table': 'curso_tipo',
            },
        ),
        migrations.CreateModel(
            name='CursoTipoDictado',
            fields=[
                ('curtip_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('curtip_vcNombre', models.CharField(max_length=16, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de dictado',
                'verbose_name_plural': 'Tipos de dictado',
                'db_table': 'curso_tipodictado',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('plaest_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('plaest_vcCodigo', models.CharField(max_length=8, unique=True, verbose_name='Código')),
                ('plaest_vcRR', models.CharField(max_length=16, verbose_name='Nombre')),
                ('plaest_dVigencia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('plaest_iCreditos', models.IntegerField(blank=True, default=0, verbose_name='Créditos')),
                ('plaest_bActivo', models.IntegerField(default=1, verbose_name='Activo')),
                ('esc_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.escuela', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'Plan de estudio',
                'verbose_name_plural': 'Planes de estudio',
                'db_table': 'plan_estudio',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('gru_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('gru_iNumero', models.IntegerField(verbose_name='Número de grupo')),
                ('cur_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso', verbose_name='Curso')),
                ('sem_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vicerrectorado.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='CursoPrerequisito',
            fields=[
                ('curpre_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cur_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso', verbose_name='Curso')),
                ('req_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_iCodigo', to='escuela.curso', verbose_name='Requisito')),
            ],
            options={
                'verbose_name': 'Pre requisito',
                'verbose_name_plural': 'Prerequisitos',
                'db_table': 'curso_prerequisito',
            },
        ),
        migrations.CreateModel(
            name='CursoHorasDictado',
            fields=[
                ('curhor_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('curhor_iHoras', models.IntegerField(verbose_name='Horas')),
                ('cur_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso', verbose_name='Curso')),
                ('curtip_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cursotipo', verbose_name='Tipo de curso')),
            ],
            options={
                'verbose_name': 'Horas de dictado de curso',
                'verbose_name_plural': 'Horas de dictado de cursos',
                'db_table': 'curso_horasdictado',
            },
        ),
        migrations.CreateModel(
            name='CursoEquivalente',
            fields=[
                ('cureqi_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso', verbose_name='Curso')),
                ('equ_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equ_iCodigo', to='escuela.curso', verbose_name='Curso equivalente')),
            ],
            options={
                'verbose_name': 'Curso equivalente',
                'verbose_name_plural': 'Cursos equivalentes',
                'db_table': 'curso_equivalente',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='curtip_iCodigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cursotipo', verbose_name='Tipo de acceso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='plaest_iCodigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.planestudio', verbose_name='Plan de estudio'),
        ),
    ]
