# Generated by Django 4.2.6 on 2023-11-14 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_alter_cursotipo_curtip_icodigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='gru_iTope',
            field=models.IntegerField(default=0, verbose_name='Tope de alumnos'),
        ),
        migrations.AlterField(
            model_name='cursotipo',
            name='curtip_iCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='plaest_dVigencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='plaest_vcRR',
            field=models.CharField(max_length=16, verbose_name='Resolución rectoral'),
        ),
    ]
