# Generated by Django 4.2.7 on 2023-11-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAcademica',
            fields=[
                ('areaca_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('areaca_vcCodigo', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('areaca_vcNombre', models.CharField(max_length=64, unique=True, verbose_name='Nombre')),
                ('areaca_bActivo', models.IntegerField(default=1, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Área académica',
                'verbose_name_plural': 'Áreas académicas',
                'db_table': 'area_academica',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dia_iNumero', models.IntegerField(verbose_name='Número')),
                ('dia_vcNombre', models.CharField(max_length=16, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Día',
                'verbose_name_plural': 'Días',
                'db_table': 'dia',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('fac_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fac_vcCodigo', models.CharField(max_length=64, unique=True, verbose_name='Código')),
                ('fac_vcNombre', models.CharField(max_length=64, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'facultad',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('esc_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('esc_vcCodigo', models.CharField(max_length=16, unique=True, verbose_name='Código')),
                ('esc_vcNombre', models.CharField(max_length=96, unique=True, verbose_name='Nombre')),
                ('esc_bActivo', models.IntegerField(default=1, verbose_name='Activo')),
                ('areaca_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.areaacademica', verbose_name='Área académica')),
                ('fac_iCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'escuela',
            },
        ),
    ]
