# Generated by Django 4.2.7 on 2023-11-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='areaca_iCodigo',
            field=models.ForeignKey(limit_choices_to={'areaca_bActivo': 1}, on_delete=django.db.models.deletion.CASCADE, to='general.areaacademica', verbose_name='Área académica'),
        ),
    ]
