# Generated by Django 4.2.6 on 2023-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_escuela_areaca_icodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='fac_iCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
