# Generated by Django 4.2.7 on 2023-11-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('sem_iCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sem_vcCodigo', models.CharField(max_length=8, verbose_name='Código')),
                ('sem_cActivo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'semestre',
            },
        ),
    ]
