# Generated by Django 4.2.6 on 2023-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicerrectorado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='sem_iCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
