# Generated by Django 4.2.6 on 2023-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_aula_aul_imgimage_aula_aul_vclatitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='aul_imgImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='aulas', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='local',
            name='loc_iCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
